function letterHTML(id, content) {
  var body = '<div class="letter-icon">&#127876;</div>';
  if (content && content.text) {
    body += '<h1>Your Christmas Letter</h1><div class="letter-text">' + escapeHtml(content.text) + '</div>';
  }
  if (content && content.audioUrl) {
    body += '<div class="audio-section"><div class="audio-label">&#127925; Listen to your letter</div><audio controls preload="metadata"><source src="' + escapeHtml(content.audioUrl) + '" type="audio/mpeg"></audio></div>';
  }
  if (!content || (!content.text && !content.audioUrl)) {
    body = '<div class="empty-icon">&#127876;</div><div class="empty">This letter is not ready yet. Please check back soon.</div>';
  }
  return '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Christmas Letter - ' + escapeHtml(id) + ' - V I Key</title><style>:root{--bg-color:#121212;--card-bg:#1a1a1a;--gold:#d4af37;--text-color:#e0e0e0;--text-muted:#aaaaaa}*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background-color:var(--bg-color);background-image:linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)),url(\'https://pub-07ed0b0955a4401f9956c3ca7a33c40e.r2.dev/scroll.png\');background-size:cover;background-position:center;background-attachment:fixed;color:var(--text-color);line-height:1.8;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.letter-card{background-color:rgba(26,26,26,0.85);border:1px solid #2a2a2a;border-radius:12px;padding:40px 32px;max-width:500px;width:100%;text-align:center}.letter-icon{font-size:3rem;margin-bottom:20px}.letter-card h1{color:var(--gold);font-size:1.5rem;font-weight:500;margin-bottom:24px;letter-spacing:1px}.letter-text{color:var(--text-color);font-size:1.05rem;margin-bottom:30px;white-space:pre-wrap;text-align:left}.audio-section{margin-top:24px;padding-top:24px;border-top:1px solid #2a2a2a}.audio-label{color:var(--gold);font-size:0.9rem;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px}audio{width:100%;margin-top:8px}.footer{margin-top:30px;color:var(--text-muted);font-size:0.8rem}.footer a{color:var(--gold);text-decoration:none}.empty{color:var(--text-muted);font-size:1rem;padding:40px 0}.empty-icon{font-size:3rem;margin-bottom:16px}@media(max-width:480px){.letter-card{padding:30px 20px}.letter-card h1{font-size:1.3rem}.letter-text{font-size:1rem}}</style></head><body><div class="letter-card">' + body + '<div class="footer"><a href="https://wa.me/447526345287">V I Key</a></div></div></body></html>';
}
